### ISSUE TITLE
有一些可以补充的todo

### ISSUE THREAD

**Issue by buaahsh** [wwj718/deepThought#1]
hi wwj718,我前段时间也看到了ChatterBot,确实他逻辑、代码比较清楚、简单。
聊天语料的话，我觉得还可以尝试爬一下微博，贴吧的对话语料。也许会比较有用
还有一个问题就是，聊天语料多了之后效率怎么样，现在在match 的时候是找到query一一算相似度。可能语料比较多了就要考虑这个问题了。

**Comment by wwj718** [comment]
@buaahsh 哈哈，可以一起来折腾，效率确实值得考虑，ChatterBot的issue里好像有人问过这个问题。后期可以用类似搜索引擎的思路来做匹配，诸如elasticsearch
我准备发起一个openbot的项目，技术和语料库一起开源，大家可以一起训练它，我昨晚已经把bot写为RESTful服务了，这部分写入readme的**语料库**里了

**Comment by buaahsh** [comment]
恩恩，可以一起来搞啊~
不过最近要找工作可能事情有些多，等稳定下来了，可以参与进去。 :)

**Comment by kapoyegou** [comment]
关于语料库，可以用一些口语教学教材？我最近也想学着写个聊天机器人，然后目前的想法是也不是非得以平时聊天为主，可以先从某个主题入手，类似于人工服务的角色。想法会不会太简单或是很幼稚……

**Comment by wwj718** [comment]
@kapoyegou 我昨天傍晚骑车回去的路上恰好在考虑这个问题。
我目前把bot简单分为两种，闲聊型和助理型。闲聊型用ChatterBot就开箱可用，口语教学教材是可直接用来训练机器人的
机器客服我归类到助理型，它需要领域知识，我想通过intent和entity这两个概念，把自然语言对接到领域业务/数据，通过nlp解析后，得到命名实体，通过模式匹配/机器学习找关联，进而触发intent，intent就可以关联到领域知识，诸如`查询用户余额`

**Comment by wwj718** [comment]
@buaahsh  期待一起挖坑 😄

**Comment by upup78** [comment]
我是个新人，关注ChatBot项目一个月了，也在想加入一些lstm等的概念，做成机器客服。很想加入，和你们一起。

**Comment by wwj718** [comment]
欢迎的啊，我有几个chatbot的群，国内折腾这块的大多都在群里了，可以加个微信拉你进群

**Comment by upup78** [comment]
我微信号是bigwing78。期待加入！

**Comment by chenjun0210** [comment]
最近也在借鉴chatbot，很不错，共同学习~~~

**Comment by wwj718** [comment]
@upup78  已加好友 😄

**Comment by kapoyegou** [comment]
@wwj718 我github玩的不熟，看到邮件都不知道是有人在回复~~  好囧  能不能也加下我 cr00guai

**Comment by wwj718** [comment]
@kapoyegou 已加好友 😄

**Comment by mimilol** [comment]
我目前也在研究chtterbot,大牛可以不可以带上我QAQ，mimi7211847
